version: '3.7'
services:
  mrcp:
    image: arthurma/unimrcp:0.0.3-alpha
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib/:/usr/local/unimrcp/lib 
  nats:
    image: nats
    ports:
      - "4222:4222"
  #redis:
  #  image: redis:alpine3.10
  #  ports:
  #    - "6379:6379"
  controller:
    build:
      context: .
    command: "-c /config"
    ports:
      - "8080:8080"
    depends_on:
      - nats
      # - mongo
    volumes:
     - type: bind
       source: ./config
       target: /config
