apiVersion: v1
kind: Service
metadata:
  name: svc-bella
  namespace: backend
  labels:
    svc: bella
    group: backend
    owner: arthur
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30100
  selector:
    app: bella
